
'use client';

import { Button } from "@/components/ui/button";
import { Incident } from "@/types";
import { jsPDF } from "jspdf";
import { FileDown, Loader2 } from "lucide-react";
import { useState } from "react";

export function PDFExportButton({ incident }: { incident: Incident }) {
    const [loading, setLoading] = useState(false);

    const generatePDF = async () => {
        setLoading(true);
        try {
            const doc = new jsPDF();
            const margin = 20;
            let y = 20;

            // Header
            doc.setFontSize(22);
            doc.text("Incident Report", margin, y);
            y += 10;
            doc.setFontSize(10);
            doc.text("Generated by Melting Ice", margin, y);
            y += 15;

            // Meta
            doc.setFontSize(12);
            doc.setFont("helvetica", "bold");
            doc.text("Reference ID:", margin, y);
            doc.setFont("helvetica", "normal");
            doc.text(incident.id, margin + 35, y);
            y += 8;

            doc.setFont("helvetica", "bold");
            doc.text("Date/Time:", margin, y);
            doc.setFont("helvetica", "normal");
            doc.text(new Date(incident.data.datetime).toLocaleString(), margin + 35, y);
            y += 8;

            if (incident.data.location) {
                doc.setFont("helvetica", "bold");
                doc.text("Location:", margin, y);
                doc.setFont("helvetica", "normal");
                const locStr = `${incident.data.location.lat?.toFixed(5)}, ${incident.data.location.lng?.toFixed(5)}`;
                doc.text(locStr, margin + 35, y);
                y += 8;
                if (incident.data.location.address_manual) {
                    doc.text(incident.data.location.address_manual, margin + 35, y);
                    y += 8;
                }
            }

            y += 10;
            doc.setDrawColor(200);
            doc.line(margin, y, 190, y);
            y += 10;

            // Narrative
            doc.setFontSize(14);
            doc.text("Narrative/Description", margin, y);
            y += 8;
            doc.setFontSize(11);
            const splitText = doc.splitTextToSize(incident.data.description || "No description provided.", 170);
            doc.text(splitText, margin, y);
            y += (splitText.length * 5) + 10;

            // Evidence Log
            doc.setFontSize(14);
            doc.text("Evidence Log", margin, y);
            y += 8;

            const attachments = incident.data.attachments || [];
            if (attachments.length === 0) {
                doc.setFontSize(11);
                doc.text("No attachments.", margin, y);
            } else {
                doc.setFontSize(10);
                attachments.forEach((att, i) => {
                    doc.setFont("helvetica", "bold");
                    doc.text(`item #${i + 1}: ${att.original_name}`, margin, y);
                    y += 5;
                    doc.setFont("helvetica", "normal");
                    doc.text(`Type: ${att.type} | Size: ${(att.size / 1024).toFixed(1)} KB`, margin + 5, y);
                    y += 5;
                    if (att.stripped) {
                        doc.setTextColor(0, 150, 0);
                        doc.text("[METADATA STRIPPED]", margin + 5, y);
                        doc.setTextColor(0, 0, 0);
                        y += 5;
                    }
                    if (att.sha256_hash) {
                        doc.setFont("courier");
                        doc.text(`SHA256: ${att.sha256_hash}`, margin + 5, y);
                        doc.setFont("helvetica");
                        y += 5;
                    }
                    y += 5;
                });
            }

            // Disclaimer
            y = 280; // Bottom
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text("This report was generated offline. Do not alter this file to maintain chain of custody integrity.", margin, y);

            doc.save(`report-${incident.id.substring(0, 8)}.pdf`);
        } catch (e) {
            console.error(e);
            alert("Error generating PDF");
        } finally {
            setLoading(false);
        }
    };

    return (
        <Button onClick={generatePDF} disabled={loading} variant="outline" className="w-full border-blue-500 text-blue-400 hover:bg-blue-950">
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4 mr-2" />}
            Generate Case Packet (PDF)
        </Button>
    );
}
